### ISSUE TITLE
How to get an encoded video's duration?

### ISSUE THREAD

**Issue by monstatw** [southworkscom/azure-sdk-for-media-services-java-samples#5]
Hi,

Is there any way I can get the duration of an encoded media content?

I've browsed the [java doc](http://azure.github.io/azure-sdk-for-java/) but found nothing related to it.

**Comment by rnrneverdies** [comment]
This cannot be done by using the AMS Java SDK

You should download the manifest, parse it and look up the duration in there. 

[Here](https://github.com/Azure/azure-sdk-for-media-services-extensions/blob/bfbf9ef111f0bb71f6906dab7bcdc61432b3dd1a/MediaServices.Client.Extensions/IAssetExtensions.cs#L93), you can find a extension method used in .NET extension library which does exactly what you want. 

Currently, there is no extension library available for Java SDK.

Hope this helps.

**Comment by monstatw** [comment]
Thank you @rnrneverdies , I'll try downloading the manifest and parsing it.

**Comment by monstatw** [comment]
For whom need to get duration using Java, below is my code sample. I've skip http and exception handling details.
```java
        ListResult<AssetFileInfo> assetFiles = mediaService.list(AssetFile.list(
                mediaService.get(Asset.get(encodedOutputAssetId)).getAssetFilesLink()));
        for (AssetFileInfo file : assetFiles) {
            if (file.getName().toLowerCase().endsWith("_metadata.xml")) {
                String locatorPath = mediaService.get(Locator.get(locatorInfoId)).getPath();
                String metadataUri = locatorPath + file.getName();
                InputStream metadataIS = Http.get(metadataUri).andReturn().asInputStream();
                Document metadataDom = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(metadataIS);
                Element assetFileNode = (Element) metadataDom.getElementsByTagName("AssetFile").item(0);
                
                //duration is ISO 8601 Durations format
                String duration = assetFileNode.getAttribute("Duration");
            }
        }
```
