### ISSUE TITLE
How to add addJobNotificationSubscription to the Job that is created

### ISSUE THREAD

**Issue by rajadileepkolli** [southworkscom/azure-sdk-for-media-services-java-samples#8]
How to add addJobNotificationSubscription to the Job that is created while encoding, Instead of waiting for the job to completed  like in [checkStatus](https://github.com/southworkscom/azure-sdk-for-media-services-java-samples/blob/master/azure-media-dynamic-encryption-aes/src/main/java/com/microsoft/windowsazure/services/media/samples/contentprotection/aes/Program.java#L405-L420) , we will get notification once Job is completed, this helps to utilize resources effectively.

Please help me proceed further

**Comment by rnrneverdies** [comment]
Hi @rajadileepkolli 

This unit test may help you: https://github.com/Azure/azure-sdk-for-java/blob/0.9/services/azure-media/src/test/java/com/microsoft/windowsazure/services/media/JobIntegrationTest.java#L158

Regards.

**Comment by rajadileepkolli** [comment]
@rnrneverdies Thanks for the update, its really useful .

Do we have any other way to achieve apart from using Microsoft QueueServices

**Comment by rnrneverdies** [comment]
AFAIK, No.

**Comment by rajadileepkolli** [comment]
Thanks for the information @rnrneverdies
